{{- range .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
    {{- include "cloudkitchen.labels" $ | nindent 4 }}
spec:
  replicas: {{ .replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
        {{- include "cloudkitchen.labels" $ | nindent 8 }}
      {{- if .disableOtel }}
      annotations:
        instrumentation.opentelemetry.io/inject-python: "false"
      {{- end }}
    spec:
      
      serviceAccountName: {{ .serviceAccount | default "cloudkitchen-default" }}
      
      securityContext:
        runAsNonRoot: true
        runAsUser: {{ .runAsUser | default 1000 }}
        runAsGroup: {{ .runAsUser | default 1000 }}
        fsGroup: {{ .runAsUser | default 1000 }}
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: {{ .name }}
          image: {{ include "cloudkitchen.image" (dict "root" $ "svc" .) | quote }}
          imagePullPolicy: IfNotPresent
          
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          ports:
            - containerPort: {{ .port }}
        
          envFrom:
            - configMapRef:
                name: cloudkitchen-config
            - secretRef:
                name: cloudkitchen-secrets
         
          readinessProbe:
            tcpSocket:
              port: {{ .port }}
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            tcpSocket:
              port: {{ .port }}
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
---
{{- end }}
