apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  labels:
    {{- include "cloudkitchen.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.eso.region | quote }}
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudkitchen-secrets
  labels:
    {{- include "cloudkitchen.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: cloudkitchen-secrets
    creationPolicy: Owner
  
  dataFrom:
    - extract:
        key: {{ .Values.eso.appSecretName | quote }}

  data:
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: {{ .Values.eso.dbSecretName | quote }}
        property: password
