
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudkitchen-default
  labels:
    {{- include "cloudkitchen.labels" . | nindent 4 }}
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.irsa.aiRoleArn | quote }}
  labels:
    {{- include "cloudkitchen.labels" . | nindent 4 }}
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: order
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.irsa.orderRoleArn | quote }}
  labels:
    {{- include "cloudkitchen.labels" . | nindent 4 }}
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.irsa.authRoleArn | quote }}
  labels:
    {{- include "cloudkitchen.labels" . | nindent 4 }}
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.irsa.esoRoleArn | quote }}
  labels:
    {{- include "cloudkitchen.labels" . | nindent 4 }}
