apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudkitchen-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cloudkitchen
  source:
    repoURL: https://github.com/Cloudkitchen007/cloudkitchen-gitops.git
    targetRevision: dev
    path: helm/cloudkitchen
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
