apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudkitchen-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cloudkitchen
  source:
    repoURL: https://github.com/Cloudkitchen007/cloudkitchen-gitops.git
    targetRevision: main
    path: helm/cloudkitchen
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
