apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cloudkitchen
  namespace: argocd
spec:
  description: CloudKitchen backend microservices
  sourceRepos:
    - "*"           
  destinations:
    - server: https://kubernetes.default.svc
      namespace: production
    - server: https://kubernetes.default.svc
      namespace: dev
    - server: https://kubernetes.default.svc
      namespace: prod
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
